// Simple code that gets the job done by Orange
// Set up environment 
var aSiteYouVisit = window.location.href;
var waitingTime = "480";
var headers = new Headers();

var init = { method: 'GET',
	         headers: headers,
	         mode: 'cors',
	         cache: 'default' };

var updateJSON = new Request('https://test.reveb.la/index.json', init);
var defaultObj = {
    time: Date.now(), 
    url: "www.google", 
    q95: "00000",
};

var sites = {
  "sites": [
    [
      "q1045245",
      "office.com/"
    ],
    [
      "q1046951",
      "www.target.com"
    ],
    [
      "q10854572",
      "www.hmv.com"
    ],
    [
      "q11148",
      "www.theguardian.com"
    ],
    [
      "q11149",
      "www.independent.co.uk/"
    ],
    [
      "q11229109",
      "linecorp.com/"
    ],
    [
      "q1136",
      "www.reddit.com"
    ],
    [
      "q1139037",
      "www.mediafire.com/"
    ],
    [
      "q11463",
      "www.adobe.com/"
    ],
    [
      "q116933",
      "vk.com"
    ],
    [
      "q1308139",
      "www.thedailybeast.com"
    ],
    [
      "q130879",
      "www.reuters.com"
    ],
    [
      "q130879",
      "jp.reuters.com"
    ],
    [
      "q130879",
      "uk.reuters.com/"
    ],
    [
      "q130879",
      "fr.reuters.com"
    ],
    [
      "q130879",
      "ru.reuters.com/"
    ],
    [
      "q130879",
      "in.reuters.com"
    ],
    [
      "q131478",
      "www.spiegel.de"
    ],
    [
      "q131566",
      "www.ieee.org/"
    ],
    [
      "q1359568",
      "www.alibaba.com/"
    ],
    [
      "q139103",
      "sfgate.com/"
    ],
    [
      "q139103",
      "www.sfchronicle.com/"
    ],
    [
      "q13977",
      "www.bloomberg.com/"
    ],
    [
      "q1416215",
      "godaddy.com"
    ],
    [
      "q142539",
      "www.dropbox.com/"
    ],
    [
      "q147662",
      "www.zara.com/"
    ],
    [
      "q14772",
      "www.baidu.com/"
    ],
    [
      "q151888",
      "www.peta.org"
    ],
    [
      "q152057",
      "www.bp.com/"
    ],
    [
      "q15401349",
      "www.zendesk.com/"
    ],
    [
      "q15401349",
      "www.zendesk.co.jp/"
    ],
    [
      "q15401349",
      "www.zendesk.co.uk/"
    ],
    [
      "q1544247",
      "cnet.com/"
    ],
    [
      "q154950",
      "www.shell.com"
    ],
    [
      "q154950",
      "www.shell.co.uk/"
    ],
    [
      "q156238",
      "www.exxonmobil.com"
    ],
    [
      "q15630787",
      "www.voxespana.es/"
    ],
    [
      "q156376",
      "www.vimeo.com/"
    ],
    [
      "q157064",
      "puma.com"
    ],
    [
      "q157118",
      "natgeotv.com"
    ],
    [
      "q157118",
      "www.nationalgeographic.com/tv/"
    ],
    [
      "q160054",
      "www.axa.com/"
    ],
    [
      "q160120",
      "www.huawei.com/"
    ],
    [
      "q160120",
      "hwww.vmall.com"
    ],
    [
      "q160746",
      "www.nestle.com"
    ],
    [
      "q166032",
      "washingtonpost.com"
    ],
    [
      "q169925",
      "www.mozilla.org"
    ],
    [
      "q170484",
      "www.lego.com/"
    ],
    [
      "q173395",
      "www.cisco.com"
    ],
    [
      "q17459",
      "fandom.com"
    ],
    [
      "q17459",
      "wikia.com"
    ],
    [
      "q17460900",
      "Zoom.US"
    ],
    [
      "q17460900",
      "Zoom.com"
    ],
    [
      "q182477",
      "www.nvidia.com"
    ],
    [
      "q183399",
      "www.ft.com"
    ],
    [
      "q18572033",
      "sputniknews.com/"
    ],
    [
      "q18572033",
      "mundo.sputniknews.com/"
    ],
    [
      "q18572033",
      "sputnik-abkhazia.info/"
    ],
    [
      "q18572033",
      "sputnik-abkhazia.ru/"
    ],
    [
      "q18572033",
      "arabic.sputniknews.com/"
    ],
    [
      "q18572033",
      "armeniasputnik.am/"
    ],
    [
      "q18572033",
      "ru.armeniasputnik.am/"
    ],
    [
      "q18572033",
      "sputnik.az/"
    ],
    [
      "q18572033",
      "ru.sputnik.az/"
    ],
    [
      "q18572033",
      "bel.sputnik.by/"
    ],
    [
      "q18572033",
      "sputnik.by/"
    ],
    [
      "q18572033",
      "br.sputniknews.com/"
    ],
    [
      "q18572033",
      "sputniknews.cn/"
    ],
    [
      "q18572033",
      "cz.sputniknews.com/"
    ],
    [
      "q18572033",
      "dari.sputniknews.com/"
    ],
    [
      "q18572033",
      "de.sputniknews.com/"
    ],
    [
      "q18572033",
      "sputnik-news.ee/"
    ],
    [
      "q18572033",
      "ru.sputnik-news.ee/"
    ],
    [
      "q18572033",
      "fr.sputniknews.com/"
    ],
    [
      "q18572033",
      "sputnik-georgia.com/"
    ],
    [
      "q18572033",
      "sputnik-georgia.ru/"
    ],
    [
      "q18572033",
      "it.sputniknews.com/"
    ],
    [
      "q18572033",
      "jp.sputniknews.com/"
    ],
    [
      "q18572033",
      "sputniknews.kz/"
    ],
    [
      "q18572033",
      "ru.sputniknews.kz/"
    ],
    [
      "q18572033",
      "kr.sputniknews.com/"
    ],
    [
      "q18572033",
      "krd.sputniknews.com/"
    ],
    [
      "q18572033",
      "sputnik.kg/"
    ],
    [
      "q18572033",
      "ru.sputnik.kg/"
    ],
    [
      "q18572033",
      "sputniknewslv.com/"
    ],
    [
      "q18572033",
      "ru.sputniknewslv.com/"
    ],
    [
      "q18572033",
      "sputnik.md/"
    ],
    [
      "q18572033",
      "ro.sputnik.md/"
    ],
    [
      "q18572033",
      "ru.sputnik.md/"
    ],
    [
      "q18572033",
      "oz.sputniknews-uz.com/"
    ],
    [
      "q18572033",
      "sputniknews-uz.com/"
    ],
    [
      "q18572033",
      "ru.sputniknews-uz.com/"
    ],
    [
      "q18572033",
      "pashto.sputniknews.com/"
    ],
    [
      "q18572033",
      "ir.sputniknews.com/"
    ],
    [
      "q18572033",
      "pl.sputniknews.com/"
    ],
    [
      "q18572033",
      "rs.sputniknews.com/"
    ],
    [
      "q18572033",
      "sputnik-ossetia.com/"
    ],
    [
      "q18572033",
      "sputnik-ossetia.ru/"
    ],
    [
      "q18572033",
      "sputnik-tj.com/"
    ],
    [
      "q18572033",
      "ru.sputnik-tj.com/"
    ],
    [
      "q18572033",
      "tr.sputniknews.com/"
    ],
    [
      "q18572033",
      "vn.sputniknews.com/"
    ],
    [
      "q186068",
      "www.foxnews.com/"
    ],
    [
      "q18643672",
      "www.jio.com"
    ],
    [
      "q188326",
      "www.hm.com/"
    ],
    [
      "q188515",
      "www.latimes.com/"
    ],
    [
      "q189021",
      "ted.com"
    ],
    [
      "q190464",
      "www.hsbc.com/"
    ],
    [
      "q193701",
      "www.spacex.com"
    ],
    [
      "q1957782",
      "www.consumerreports.org/"
    ],
    [
      "q19900",
      "www.oracle.com"
    ],
    [
      "q19900",
      "www.oracle.com/tr/"
    ],
    [
      "q204839",
      "www.xinhuanet.com"
    ],
    [
      "q204839",
      "www.news.cn"
    ],
    [
      "q20716",
      "www.samsung.com/"
    ],
    [
      "q207708",
      "www.ign.com"
    ],
    [
      "q207708",
      "tr.ign.com/"
    ],
    [
      "q20877087",
      "www.vox.com"
    ],
    [
      "q208875",
      "www.thesun.co.uk/"
    ],
    [
      "q209330",
      "www.instagram.com/"
    ],
    [
      "q2103926",
      "www.unitedhealthgroup.com/"
    ],
    [
      "q210534",
      "www.dailymail.co.uk/"
    ],
    [
      "q2117484",
      "www.taobao.com"
    ],
    [
      "q213660",
      "www.linkedin.com/"
    ],
    [
      "q2155442",
      "www.theverge.com"
    ],
    [
      "q217583",
      "www.berkshirehathaway.com/"
    ],
    [
      "q217776",
      "www.espn.com/"
    ],
    [
      "q217776",
      "www.espn.co.uk/"
    ],
    [
      "q220072",
      "www.itv.com"
    ],
    [
      "q22099300",
      "www.panda.tv/"
    ],
    [
      "q2283",
      "www.microsoft.com/"
    ],
    [
      "q22868",
      "www.rt.com"
    ],
    [
      "q22907849",
      "discord.com/"
    ],
    [
      "q22907849",
      "discordapp.com/"
    ],
    [
      "q2299611",
      "www.yelp.com/"
    ],
    [
      "q2299611",
      "www.yelp.co.uk"
    ],
    [
      "q23548",
      "www.nasa.gov/"
    ],
    [
      "q23633",
      "www.hbo.com"
    ],
    [
      "q2407962",
      "lifehacker.com/"
    ],
    [
      "q25161472",
      "www.forbes.com"
    ],
    [
      "q255381",
      "www.pinterest.com/"
    ],
    [
      "q270478",
      "www.digg.com"
    ],
    [
      "q27585",
      "www.aol.com"
    ],
    [
      "q2777905",
      "www.academia.edu"
    ],
    [
      "q2829108",
      "www.tmall.com"
    ],
    [
      "q283637",
      "cpanel.net/"
    ],
    [
      "q286707",
      "www.businessinsider.com/"
    ],
    [
      "q287171",
      "abcnews.go.com/"
    ],
    [
      "q2913725",
      "thenextweb.com"
    ],
    [
      "q306144",
      "nginx.org/"
    ],
    [
      "q306527",
      "www.wikihow.com/Main-Page"
    ],
    [
      "q30873",
      "www.dell.com/"
    ],
    [
      "q3090589",
      "www.change.org/"
    ],
    [
      "q3109740",
      "www.politico.com"
    ],
    [
      "q312",
      "www.apple.com/"
    ],
    [
      "q312",
      "www.apple.com.cn/"
    ],
    [
      "q322579",
      "www.united-internet.com"
    ],
    [
      "q326704",
      "www.easports.com/fifa"
    ],
    [
      "q328840",
      "www.visa.com/"
    ],
    [
      "q328840",
      "www.visa.com.tr/"
    ],
    [
      "q3295867",
      "www.coca-colacompany.com/"
    ],
    [
      "q3295867",
      "www.coca-colaturkiye.com/"
    ],
    [
      "q334800",
      "pepsico.com"
    ],
    [
      "q34433",
      "www.ox.ac.uk/"
    ],
    [
      "q3482689",
      "www.shutterstock.com/"
    ],
    [
      "q3536160",
      "www.webmd.com/"
    ],
    [
      "q35525",
      "www.whitehouse.gov"
    ],
    [
      "q355",
      "www.facebook.com"
    ],
    [
      "q35794",
      "www.cam.ac.uk/"
    ],
    [
      "q3598926",
      "www.jd.com/"
    ],
    [
      "q359",
      "wikileaks.org/"
    ],
    [
      "q364",
      "github.com"
    ],
    [
      "q367466",
      "marvel.com"
    ],
    [
      "q37156",
      "www.ibm.com/"
    ],
    [
      "q37230",
      "www.cia.gov/"
    ],
    [
      "q3884",
      "www.amazon.com"
    ],
    [
      "q3884",
      "www.amazon.it"
    ],
    [
      "q3884",
      "www.amazon.co.uk"
    ],
    [
      "q3884",
      "www.amazon.es"
    ],
    [
      "q3884",
      "www.amazon.in"
    ],
    [
      "q3884",
      "www.amazon.fr"
    ],
    [
      "q3884",
      "www.amazon.ca"
    ],
    [
      "q3884",
      "www.amazon.nl"
    ],
    [
      "q3884",
      "www.amazon.com.tr"
    ],
    [
      "q3884",
      "www.amazon.co.jp"
    ],
    [
      "q3884",
      "www.amazon.de"
    ],
    [
      "q3884",
      "www.amazon.com.au"
    ],
    [
      "q3884",
      "www.amazon.com.br"
    ],
    [
      "q39057054",
      "bongacams.com/"
    ],
    [
      "q39681",
      "www.usatoday.com/"
    ],
    [
      "q4052640",
      "venturebeat.com"
    ],
    [
      "q40629",
      "myspace.com"
    ],
    [
      "q40984",
      "www.skype.com/"
    ],
    [
      "q430526",
      "evernote.com"
    ],
    [
      "q4555537",
      "www.twitch.tv/"
    ],
    [
      "q459965",
      "www.caterpillar.com/"
    ],
    [
      "q461",
      "archive.org/"
    ],
    [
      "q467752",
      "www.verizon.com/"
    ],
    [
      "q46807",
      "timesofindia.indiatimes.com/"
    ],
    [
      "q4695024",
      "www.ahava.com/"
    ],
    [
      "q473503",
      "disqus.com/"
    ],
    [
      "q4778915",
      "www.cloudflare.com/"
    ],
    [
      "q478214",
      "www.tesla.com/"
    ],
    [
      "q483551",
      "www.walmart.com"
    ],
    [
      "q483959",
      "www.paypal.com"
    ],
    [
      "q485639",
      "naver.com"
    ],
    [
      "q4880667",
      "www.behance.net/"
    ],
    [
      "q489709",
      "www.apache.org"
    ],
    [
      "q489921",
      "www.mastercard.com/"
    ],
    [
      "q489921",
      "www.mastercard.us/en-us.html"
    ],
    [
      "q49108",
      "web.mit.edu/"
    ],
    [
      "q49112",
      "www.yale.edu"
    ],
    [
      "q493556",
      "www.alipay.com/"
    ],
    [
      "q50009",
      "www.elpais.com/"
    ],
    [
      "q5003490",
      "www.buzzfeed.com"
    ],
    [
      "q51711",
      "www.quora.com"
    ],
    [
      "q51711",
      "bn.quora.com"
    ],
    [
      "q5276019",
      "www.digitaltrends.com/"
    ],
    [
      "q5281",
      "yandex.com/"
    ],
    [
      "q5281",
      "яндекс.рф/"
    ],
    [
      "q5281",
      "ya.ru/"
    ],
    [
      "q5281",
      "yandex.ru"
    ],
    [
      "q52",
      "www.wikipedia.org/"
    ],
    [
      "q5416738",
      "www.eventbrite.com"
    ],
    [
      "q5416738",
      "www.eventbrite.co.uk/"
    ],
    [
      "q545966",
      "bandcamp.com"
    ],
    [
      "q549037",
      "stackoverflow.com"
    ],
    [
      "q555925",
      "www.broadcom.com/"
    ],
    [
      "q5574625",
      "www.gofundme.com/"
    ],
    [
      "q568769",
      "SoundCloud.com"
    ],
    [
      "q570473",
      "www.mckesson.com/"
    ],
    [
      "q58024",
      "www.ebay.com"
    ],
    [
      "q58024",
      "www.ebay.co.uk/"
    ],
    [
      "q58024",
      "www.ebay.de/"
    ],
    [
      "q58024",
      "www.ebay.fr/"
    ],
    [
      "q58024",
      "www.ebay.es"
    ],
    [
      "q58024",
      "www.ebay.it"
    ],
    [
      "q593786",
      "www.btplc.com/"
    ],
    [
      "q593786",
      "www.businessdirect.bt.com/"
    ],
    [
      "q593786",
      "www.shop.bt.com/"
    ],
    [
      "q593786",
      "bttechnicalsupport.co.uk"
    ],
    [
      "q61503",
      "www.hollywoodreporter.com/hr/index.jsp"
    ],
    [
      "q619899",
      "www.mashable.com/"
    ],
    [
      "q6544704",
      "www.namecheap.com/"
    ],
    [
      "q671510",
      "www.npr.org"
    ],
    [
      "q679509",
      "www.sciencedaily.com"
    ],
    [
      "q683006",
      "www.sodastream.co.il/"
    ],
    [
      "q689141",
      "www.spotify.com"
    ],
    [
      "q7267707",
      "www.360.cn/"
    ],
    [
      "q7267707",
      "360safe.com"
    ],
    [
      "q7414",
      "thewaltdisneycompany.com"
    ],
    [
      "q7414",
      "disney.co.uk/"
    ],
    [
      "q7414",
      "www.disney.com/"
    ],
    [
      "q7501150",
      "www.shopify.com/"
    ],
    [
      "q7501150",
      "pt.shopify.com"
    ],
    [
      "q7501150",
      "www.shopify.jp"
    ],
    [
      "q7501150",
      "en.shopify.nl/"
    ],
    [
      "q7809",
      "en.unesco.org"
    ],
    [
      "q7809",
      "fr.unesco.org"
    ],
    [
      "q7809",
      "es.unesco.org"
    ],
    [
      "q7809",
      "ru.unesco.org"
    ],
    [
      "q7809",
      "ar.unesco.org"
    ],
    [
      "q7809",
      "zh.unesco.org"
    ],
    [
      "q806215",
      "www.santander.com/"
    ],
    [
      "q80978",
      "www.hp.com/"
    ],
    [
      "q81307",
      "www.greenpeace.org/international/"
    ],
    [
      "q838212",
      "www.caf.net/"
    ],
    [
      "q851422",
      "www.chinadaily.com.cn"
    ],
    [
      "q860580",
      "www.tencent.com/"
    ],
    [
      "q860580",
      "www.tencent.com/en-us/index.html"
    ],
    [
      "q866",
      "www.youtube.com"
    ],
    [
      "q907311",
      "www.netflix.com"
    ],
    [
      "q918",
      "twitter.com"
    ],
    [
      "q92526",
      "weibo.com"
    ],
    [
      "q936394",
      "www.pornhub.org"
    ],
    [
      "q938668",
      "www.sina.com"
    ],
    [
      "q9531",
      "www.bbc.com/"
    ],
    [
      "q9531",
      "www.bbc.co.uk"
    ],
    [
      "q95",
      "www.google.com/"
    ],
    [
      "q95",
      "about.google/"
    ],
    [
      "q9626",
      "www.conservatives.com/"
    ],
    [
      "q963064",
      "www.sedoholding.com/"
    ],
    [
      "q9630",
      "labour.org.uk/"
    ],
    [
      "q965133",
      "www.sohu.com"
    ],
    [
      "q965133",
      "SOHOO.COM"
    ],
    [
      "q9684",
      "www.nytimes.com/"
    ],
    [
      "q9684",
      "cn.nytimes.com/"
    ],
    [
      "q9684",
      "www.nytimes.com/es/"
    ],
    [
      "q9684",
      "www.nytimes3xbfgragh.onion/"
    ],
    [
      "q968598",
      "www.geocities.co.jp/"
    ]],};

function getData() {
	var timeNow = new Date;
	now = timeNow.getTime();
	chrome.storage.local.get(function(topSiteOfTheWeek){
		if ( !topSiteOfTheWeek.time || !topSiteOfTheWeek.url || !topSiteOfTheWeek.site ){
			chrome.storage.local.set(defaultObj);
		}

		// Find the time to keep it updated
		var newTime = topSiteOfTheWeek.time - waitingTime;
		if ( newTime < now ){
			console.log("[ Invisible Voice ]: Update needed, so updating");
            fetch(updateJSON)
                .then(response => response.json())
                .then(data => chrome.storage.local.set(data))
                .catch(error => console.log("[ Invisible Voice ]: Fetch Error", error.message ));
		}

		chrome.storage.local.get(null, function(items) {
			var allKeys = Object.keys(items);
			console.log(allKeys);
		});

        var possibleSite;
        for (possibleSite of sites.sites){
		// Then you check to see if when you visit a site it might be a top site
		    if (aSiteYouVisit.indexOf(possibleSite[1]) >= 0){
		        // Ooooh watch out, that site was sighted, set sites to the replacement!
                document.documentElement.appendChild(iframe);
                document.documentElement.appendChild(close);
                inject(possibleSite[0]);
		    	console.log("[ Invisible Voice ]: Page Replaced");
		    }
        }
	});	
}

function inject(code) {
    console.log("injecting" + code);
	document.head.prepend(changeMeta);
	iframe.src =  "https://test.reveb.la/posts/" + code + "/index.html"; 
}

document.addEventListener('click', function (event) {

	// If the clicked element doesn't have the right selector, bail
	if (!event.target.matches('#invisible-voice-button')) return;

	// Don't follow the link
	event.preventDefault();

	// Log the clicked element in the console
	console.log(event.target);
    iframe.remove();
    close.remove();
}, false);


var changeMeta = document.createElement("meta");
changeMeta.httpEquiv = "Content-Security-Policy";
changeMeta.content = "upgrade-insecure-requests";


var close = document.createElement("div");
close.id = "invisible-voice-button";
close.innerHTML = "Close";
close.style.cssText = "border: 0px; overflow: visible; padding: 0px; right: 6.54vw; top: 6.54vh; left: auto; z-index: 2147483647; position: fixed; color: #DDD; background-color: #444; font-family: 'Unica Reg', sans-serif; font-size: 24px;";

var iframe = document.createElement("iframe");
iframe.style.cssText = "border: 0px; overflow: hidden; padding: 0px; right: auto; width: 86.1vw; height: 86.1vh; top: 6.54vh; left: 6.545vw; z-index: 2147483646; box-shadow: rgba(0, 0, 0, 0.498039) 0px 3px 10px; position: fixed; background-color: #fff;";
iframe.id = "Invisible";
iframe.onkeypress = "deject();"



getData();
